# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_by',
            field=models.ManyToManyField(related_name='_user_friend_by_+', to='users.User'),
        ),
    ]
