# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_friend_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend_by',
        ),
        migrations.AddField(
            model_name='friendship',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='users.User'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='users.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='friend_to', through='users.Friendship', to='users.User'),
        ),
    ]
