# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171221_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='from_person',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_person',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friend_by',
            field=models.ManyToManyField(related_name='_user_friend_by_+', to='users.User'),
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
