# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-21 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='linkned_by',
            new_name='linked_by',
        ),
    ]
